apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nbkqi1h31-nodejs 
  janus-idp.io/tekton: nbkqi1h31-nodejs
  backstage.io/kubernetes-id: nbkqi1h31-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nbkqi1h31-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml